apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather
  namespace: argocd
spec:
  project: default
  source:
    chart: githubhelm/weather
    repoURL: ghcr.io/belalkhaledmohameed
    targetRevision: 0.1.0
    helm:
      releaseName: weather
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true


